Repository hyperf/hyperf, pull requests merged in 2020-11, with the labels that each got.

#2347 Added `waitTimeout` for ConsumerMessageInterface
  CHANGELOG-2.0.md
  src/amqp/src/Consumer.php
  src/amqp/src/Event/WaitTimeout.php
  src/amqp/src/Message/ConsumerMessage.php
  src/amqp/src/Message/ConsumerMessageInterface.php
  src/amqp/tests/ConsumerManagerTest.php
Labels: reviewing

#2788 fix call Non-static method statically
  CHANGELOG-2.0.md
  src/di/src/Aop/PropertyHandlerVisitor.php
  src/di/tests/AstTest.php
Labels: good first issue

#2866 v2.0.21
  CHANGELOG-2.0.md
  composer.json
  phpunit.xml
Labels: WIP
